"""Chat agent — flow only. Replies conversationally for casual/general input.

The supervisor routes here when the user is chatting rather than requesting a data
task (a greeting, small talk, "what can you do", or an unrelated question). The
actual reply is generated by ``tools/chat_reply.py``.
"""

from __future__ import annotations

from mito_data_agent.agents.base import finalize
from mito_data_agent.agents.state import MultiAgentState
from mito_data_agent.tools.chat_reply import generate_chat_reply


def chat_agent(state: MultiAgentState) -> dict:
    """Generate a conversational reply to the user's message."""
    prompt = state.get("user_prompt", "") or ""
    try:
        reply = generate_chat_reply(prompt)
        return finalize(
            state,
            "chat_agent",
            "success",
            {"chat_response": reply, "final_report": reply},
            "Replied conversationally.",
            input_keys=["user_prompt"],
        )
    except Exception as exc:  # noqa: BLE001 — keep the run alive
        reply = f"Sorry — I couldn't generate a reply right now ({exc})."
        return finalize(
            state,
            "chat_agent",
            "failed",
            {"chat_response": reply, "final_report": reply},
            f"Chat reply failed: {exc}",
            input_keys=["user_prompt"],
            errors=[f"Chat reply failed: {exc}"],
        )
